/** Shared FTE seed ledger for GM/STM/SA/SR views. */

function getFteSeedTransactions() {
  return [
    {
      Transaction_ID: 'FTE-TXN-20260813-0001',
      Transaction_Date: '2026-08-13',
      Transaction_Time: '08:42:15',
      Branch_Name: 'Carmen',
      Asset_ID: 'AST-LFT-003',
      Asset_Name: '2-Post Lift #3',
      Asset_Category: 'Shop Equipment',
      Transaction_Type: 'Repair',
      Description: 'Hydraulic hose kit and seal replacement after bay leak',
      serviceRenderedBy: 'In-House Mechanic',
      laborRate: 350,
      serviceHours: 4,
      laborPrice: 1400,
      partsPrice: 12350,
      total: 13750,
      Payment_Method: 'Company Card',
      Vendor_Supplier: 'Industrial Supply PH',
      Requested_By_User_ID: 'USR-STM-014',
      Approved_By_User_ID: 'USR-GM-001',
      Status: 'Posted',
    },
    {
      Transaction_ID: 'FTE-TXN-20260812-0004',
      Transaction_Date: '2026-08-12',
      Transaction_Time: '14:18:03',
      Branch_Name: 'CebuCity',
      Asset_ID: 'AST-ALN-001',
      Asset_Name: 'Wheel Aligner Heads',
      Asset_Category: 'Calibration Asset',
      Transaction_Type: 'Calibration',
      Description: 'Annual camera head calibration and certificate renewal',
      serviceRenderedBy: 'Manufacturer Tech',
      laborRate: 0,
      serviceHours: 6,
      laborPrice: 4800,
      partsPrice: 0,
      total: 4800,
      Payment_Method: 'Bank Transfer',
      Vendor_Supplier: 'Metro Cal Lab',
      Requested_By_User_ID: 'USR-TECH-027',
      Approved_By_User_ID: 'USR-STM-008',
      Status: 'Posted',
    },
    {
      Transaction_ID: 'FTE-TXN-20260811-0009',
      Transaction_Date: '2026-08-11',
      Transaction_Time: '10:05:41',
      Branch_Name: 'Bogo',
      Asset_ID: 'AST-PPE-LOT',
      Asset_Name: 'Shop PPE Restock Lot',
      Asset_Category: 'Safety Consumable',
      Transaction_Type: 'Purchase',
      Description: 'Gloves, goggles, and spill kit refill for bay ends',
      serviceRenderedBy: 'In-House Mechanic',
      laborRate: 350,
      serviceHours: 0,
      laborPrice: 0,
      partsPrice: 2650.5,
      total: 2650.5,
      Payment_Method: 'Cash',
      Vendor_Supplier: 'Safety First Depot',
      Requested_By_User_ID: 'USR-LEAD-003',
      Approved_By_User_ID: 'USR-STM-014',
      Status: 'Posted',
    },
    {
      Transaction_ID: 'FTE-TXN-20260810-0012',
      Transaction_Date: '2026-08-10',
      Transaction_Time: '16:27:55',
      Branch_Name: 'Lapux2',
      Asset_ID: 'AST-CMP-002',
      Asset_Name: 'Air Compressor Bay 2',
      Asset_Category: 'Facility Equipment',
      Transaction_Type: 'Preventive Maintenance',
      Description: 'Compressor oil change, filter set, and pressure check',
      serviceRenderedBy: 'In-House Electrician',
      laborRate: 350,
      serviceHours: 2,
      laborPrice: 700,
      partsPrice: 2420,
      total: 3120,
      Payment_Method: 'Company Card',
      Vendor_Supplier: 'AirTech Parts',
      Requested_By_User_ID: 'USR-FAC-002',
      Approved_By_User_ID: 'USR-GM-001',
      Status: 'Posted',
    },
    {
      Transaction_ID: 'FTE-TXN-20260809-0007',
      Transaction_Date: '2026-08-09',
      Transaction_Time: '09:33:12',
      Branch_Name: 'ITPark',
      Asset_ID: 'AST-TW-012',
      Asset_Name: 'Torque Wrench 1/2" TW-12',
      Asset_Category: 'Hand Tool',
      Transaction_Type: 'Tool Replacement',
      Description: 'Replace damaged torque wrench from tool crib inventory',
      serviceRenderedBy: 'Third-Party Provider',
      laborRate: 0,
      serviceHours: 0.5,
      laborPrice: 175,
      partsPrice: 4075,
      total: 4250,
      Payment_Method: 'Petty Cash',
      Vendor_Supplier: 'Tool World Cebu',
      Requested_By_User_ID: 'USR-TECH-041',
      Approved_By_User_ID: 'USR-STM-008',
      Status: 'Pending Approval',
    },
    {
      Transaction_ID: 'FTE-TXN-20260808-0015',
      Transaction_Date: '2026-08-08',
      Transaction_Time: '11:50:28',
      Branch_Name: 'Toledo',
      Asset_ID: 'AST-GEN-001',
      Asset_Name: 'Backup Generator',
      Asset_Category: 'Facility Equipment',
      Transaction_Type: 'Service Contract',
      Description: 'Monthly load test service and diesel stabilizer top-up',
      serviceRenderedBy: 'In-House Mechanic',
      laborRate: 350,
      serviceHours: 3,
      laborPrice: 1050,
      partsPrice: 5800,
      total: 6850,
      Payment_Method: 'Bank Transfer',
      Vendor_Supplier: 'PowerSafe Facilities',
      Requested_By_User_ID: 'USR-FAC-002',
      Approved_By_User_ID: 'USR-GM-001',
      Status: 'Posted',
    },
    {
      Transaction_ID: 'FTE-TXN-20260813-0018',
      Transaction_Date: '2026-08-13',
      Transaction_Time: '15:22:40',
      Branch_Name: 'CebuCity',
      Asset_ID: 'AST-LFT-007',
      Asset_Name: '2-Post Lift #1',
      Asset_Category: 'Shop Equipment',
      Transaction_Type: 'Repair',
      Description: 'Safety latch inspection and arm pad replacement',
      serviceRenderedBy: 'In-House Mechanic',
      laborRate: 350,
      serviceHours: 2,
      laborPrice: 700,
      partsPrice: 1850,
      total: 2550,
      Payment_Method: 'Company Card',
      Vendor_Supplier: 'Industrial Supply PH',
      Requested_By_User_ID: 'USR-SA-021',
      Approved_By_User_ID: '',
      Status: 'Pending Approval',
    },
  ];
}

function normalizeFteBranchKey(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ');
}

function filterFteByBranch(rows, branch) {
  const key = normalizeFteBranchKey(branch);
  if (!key) return Array.isArray(rows) ? rows.slice() : [];
  return (Array.isArray(rows) ? rows : []).filter(
    (row) => normalizeFteBranchKey(row && row.Branch_Name) === key
  );
}

module.exports = {
  getFteSeedTransactions,
  filterFteByBranch,
  normalizeFteBranchKey,
}